version: '3.3'
services:
    db:
      image: mysql:5.6
      volumes:
        - ./db_data_multitenant:/var/lib/mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 123
        MYSQL_DATABASE: multitenant
        MYSQL_USER: dba
        MYSQL_PASSWORD: 123
      ports:
        - "3306:3306"
